/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainnn;

/**
 *
 * @author mathe
 */
public class Menu extends java.awt.Panel {

    /**
     * Creates new form Menu
     */

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(null);

        jButton1.setText("Sair");
        add(jButton1);
        jButton1.setBounds(10, 220, 140, 23);

        jButton2.setText("Consultar Saldo");
        add(jButton2);
        jButton2.setBounds(10, 70, 140, 23);

        jButton3.setText("Ver Extrato");
        add(jButton3);
        jButton3.setBounds(10, 100, 140, 23);

        jButton4.setText("Saque");
        add(jButton4);
        jButton4.setBounds(10, 130, 140, 23);

        jButton5.setText("Transferência");
        add(jButton5);
        jButton5.setBounds(10, 160, 140, 23);

        jButton6.setText("Depósito");
        add(jButton6);
        jButton6.setBounds(10, 190, 140, 23);
        add(jPanel1);
        jPanel1.setBounds(220, 90, 230, 130);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
